# ----
# Site

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
# google_analytics_key:
# google_maps_javascript_api_key:
# disqus_shortname:

title: Pugsleys Place
description: We are a licensed boarding and grooming kennel that operates 7 days a week, located one mile form exit 257 off of I-94
url: "http://pugsleysplace.net"
# baseurl: http://pugsleysplace.net
logo: "/siteicon.png"
facebook:
  app_id: 286845214707296
image:
  facebook: /uploads/bulldog.jpg
# -----
# Build

paginate: 10
paginate_path: "/advice/:num/"

collections:
  - "staff_members"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image_path: /images/header2.png
      image: /images/header2.png
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      _comments:
        image: Shown in social shares and the advice list.

permalink: pretty

jekyll-archives:
  enabled:
    - categories

gems:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

call_to_actions:
  - Contact

social_icons:
  - Facebook

_comments:
  large_header: Toggles the size of the top banner.
  show_in_navigation: Toggles a link in the top banner.
  author_staff_member: The staff member writing this post.
  call_to_action: Type of request shown at the bottom of this page.
  background_image_path: Image shown in the top banner, blank for the default.
  testimonials: Update, add or remove testimonials.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  phone_extension: The digits after dialing the company phone.
  credentials: Shown as subtext on staff member summaries.
  contact_email_address: Address for the contact form to send to.
  new_window: Whether the link opens a new browser tab/window.
